#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo "usage: $0 <voting results file>"
    exit 1
fi

STAKE_FILE=stake.csv
VOTING_RESULTS_FILE=$1
if [ ! -f "$VOTING_RESULTS_FILE" ]; then
    echo "error: voting results file '$1' not found"
fi

STAKE_FILE_TMP1=$STAKE_FILE.tmp1
STAKE_FILE_TMP2=$STAKE_FILE.tmp2


cp $STAKE_FILE $STAKE_FILE_TMP1

for APPROVED_COMPENSATION_REQUEST_FILE in $(cat $VOTING_RESULTS_FILE | awk -F, '{if ($2 > 0) print $1}'); do
    sort $APPROVED_COMPENSATION_REQUEST_FILE \
        | join -t, -a1 $STAKE_FILE_TMP1 - \
        | awk -F, '{old_bal=$4; comp=$6; new_bal=old_bal+comp; printf("%s,%s,%s,%s\n", $1, $2, $3, new_bal)}' > $STAKE_FILE_TMP2 \
        && mv $STAKE_FILE_TMP2 $STAKE_FILE_TMP1
done \
    && mv $STAKE_FILE_TMP1 $STAKE_FILE

git diff $STAKE_FILE
